Add ability to get audit-log of user actions
finleap-connect/monoctl pull request #47
Opened 2022-03-18 15:39 UTC by HaniAlshikh

let administrators or people like CISOs get detailed information about user actions

2022-03-25 09:04 UTC, jastBytes requested changes

2022-03-25 09:04 UTC, jastBytes commented on cmd/monoctl/get/audit_log.go
> +	now = time.Now()
UTC?

2022-03-30 09:50 UTC, HaniAlshikh commented on cmd/monoctl/get/audit_log.go
> +	now = time.Now()
For sure, done 👍

2022-03-30 10:07 UTC, christianhuening approved these changes

2022-03-30 10:11 UTC, merged